### ISSUE TITLE
How to run the simple example with docker?

### ISSUE THREAD

**Issue by Hoohaha** [facebook/bistro#30]
I built successfully a docker image in my local. And i want to runthe simple example by docker-compose which is mentioned in the README.md. But the woker saide that `BistroWorkerHandler.cpp:755] Unable to send heartbeat to scheduler: Channel is !good()`

Bellow is my docker-compose.yml
```yml
version: "3.2"
services:
  scheduler:
    image: bistro
    working_dir: "/home/bistro/bistro"
    command: ["./cmake/Debug/server/bistro_scheduler", "--server_port=6789", "--http_server_port=6790", "--config_file=scripts/test_configs/simple", "--clean_statuses", "--CAUTION_startup_wait_for_workers=1", "--instance_node_name=scheduler"]
    ports:
      - "6789:6789"
      - "6790:6790"

  worker:
    image: bistro
    working_dir: "/home/bistro/bistro"
    command: ["./cmake/Debug/worker/bistro_worker", "--server_port=27182", "--scheduler_host=scheduler", "--scheduler_port=6789", "--worker_command=$HOME/demo_bistro_task.sh", "--data_dir=."]
    ports:
      - "27182:27182"
    links:
      - scheduler
    depends_on:
      - scheduler
```
I tried following setting for scheduler_host, that all are not working.
` --scheduler_host=scheduler`, ` --scheduler_host=::`, ` --scheduler_host=0.0.0.0`

What's the problem? Does anybody used the docker-compose?
